//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWebInternetBanking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepositoPlazo
    {
        public int CodPlazo { get; set; }
        public int CodUsuario { get; set; }
        public int CantidadPlazos { get; set; }
        public decimal TotalPagar { get; set; }
        public int CodMoneda { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
