//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marchamo
    {
        public int CodMarchamo { get; set; }
        public string Placa { get; set; }
        public int CodUsuario { get; set; }
        public decimal Monto { get; set; }
        public decimal ValorVehiculo { get; set; }
        public decimal Tasa { get; set; }
        public decimal TotalPagar { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
