//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamo
    {
        public int CodPrestamo { get; set; }
        public int CodUsuario { get; set; }
        public decimal MontoPrestamo { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public System.DateTime FechaLimite { get; set; }
        public decimal TasaInteres { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
